<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_DiastolicField</name>
   <tag></tag>
   <elementGuidId>007028de-254b-4ec3-a2b0-892e8de77170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BP_Diastolic-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BP_Diastolic-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>416d9254-36b2-49fb-8a30-5ddbcad4521e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>fc6b0bc9-8d66-4cfa-b198-f2da8ca54abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Diastolic Value</value>
      <webElementGuid>8fd741aa-39ab-4e76-96c7-f7852db7dfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>dfdb0e10-0b95-4e4a-ae09-dfafae746a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26567a88-e8f0-444a-b41c-605f276d6d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>1da82bf0-1713-45f5-bb9c-b7d84e7d9d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Diastolic Value</value>
      <webElementGuid>f5088fe5-7803-4187-baa2-ffa5dbe919c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>0ac09832-6566-412c-91a7-994968c43c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0d4183fe-e3a6-4b3e-a821-a61924ff84ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>b8500e3a-c8e5-41ba-b13f-6075180dc517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Diastolic Value</value>
      <webElementGuid>1070fccc-7c37-433f-bec3-df5890973f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>dccc0b89-ef57-4e7b-a041-d80893f07588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3b693525-4fc3-4690-89c1-4fa54d6c6041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>c7dfa99e-d338-4dc4-a64a-2a7f32f7acd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Diastolic Value</value>
      <webElementGuid>a1682a06-f5f8-47b0-9069-cada2832f777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>48aae06b-68cc-49a3-a8d8-0936a9be0627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BP_Diastolic-error']</value>
      <webElementGuid>6c6ab8a8-b752-415c-a3fd-a381ab58030e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/span/span</value>
      <webElementGuid>31e33665-d595-4b71-bb2e-c08fd37454b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diastolic'])[1]/following::span[2]</value>
      <webElementGuid>003fafc3-86c8-4727-94fc-f262159e0a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Systolic Value'])[1]/following::span[2]</value>
      <webElementGuid>f4e7b27c-a0c5-4f2c-b93d-dfd60536a1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::span[1]</value>
      <webElementGuid>d5d49f1f-e562-49b1-a175-c0510d3a14d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Age Range. Calculations are for ages over 15 &amp; under 100'])[1]/preceding::span[1]</value>
      <webElementGuid>f14f035b-c9e0-467f-9331-6f3dd2adfc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Diastolic Value']/parent::*</value>
      <webElementGuid>db56086f-4811-45a3-b085-3148ff7fa80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span</value>
      <webElementGuid>03e86f94-63a1-4275-a7c4-c6731e3c0cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BP_Diastolic-error' and (text() = 'Invalid Diastolic Value' or . = 'Invalid Diastolic Value')]</value>
      <webElementGuid>b6feede9-e611-4d2f-b815-d14c3d1303e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
