<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_SystolicField</name>
   <tag></tag>
   <elementGuidId>ff6d40be-e670-4796-9091-b17096af3ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BP_Systolic-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BP_Systolic-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9e48f11-b32d-456c-a1ed-21671ad9c8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>04208a8e-62b0-4c84-acd7-d493dbe8d521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Systolic Value</value>
      <webElementGuid>0574ec7a-11a0-4460-b80c-85fd1502e15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>7b7fb1d1-0bf1-429a-9ac8-cc03a5efc23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2d9b828-d22f-481e-9ea2-526c68de6067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>912b5efd-3107-4c1a-b9ca-0f311945dcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Systolic Value</value>
      <webElementGuid>5234b8f9-fa9a-4608-ab61-1104fc964645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>6b1b5231-e60d-47a0-a04f-ac1e97d3d6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1bba0c80-d677-408a-9abf-8ba9c9540ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>012bf153-7d52-431d-89e0-0985ccc5efe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Systolic Value</value>
      <webElementGuid>8a6ddd19-3776-4230-8e0f-b033b5ade681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>fd09615f-f074-41cd-bb25-cbbb35f163e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>914bee75-4a60-44a4-aadc-6515cf0d9d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>8482cf28-eaab-4ff0-85ca-92fa99441590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Systolic Value</value>
      <webElementGuid>b3d6110f-81e1-4379-aaa2-abc735e73ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>e2978233-9847-45f2-81b6-53334aadbb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BP_Systolic-error']</value>
      <webElementGuid>895081e5-09d8-415e-a33a-9cfe05859b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/span/span</value>
      <webElementGuid>1a19f192-b680-480c-84eb-19e5bb736678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systolic'])[1]/following::span[2]</value>
      <webElementGuid>c7c275c4-0dfc-4b9b-b3aa-61096b0dcec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systolic must be greater than Diastolic'])[1]/following::span[2]</value>
      <webElementGuid>96638ee0-d63c-46c7-8900-bfe71e0f2c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diastolic'])[1]/preceding::span[1]</value>
      <webElementGuid>d78a521b-2484-4ddf-af7e-16c392c0e6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid Diastolic Value'])[1]/preceding::span[1]</value>
      <webElementGuid>8d1f6ee9-42c2-4f96-9899-21dc6b01a263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Systolic Value']/parent::*</value>
      <webElementGuid>90d67134-3cdb-4329-9a48-34f05cdb4e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>fabba2d0-a99c-40d9-a100-3c3812a36937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BP_Systolic-error' and (text() = 'Invalid Systolic Value' or . = 'Invalid Systolic Value')]</value>
      <webElementGuid>7ee72cee-b9f3-46b0-879f-16085e1def7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
