<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_Validation_Age</name>
   <tag></tag>
   <elementGuidId>be13cc10-1073-4f4c-b3d5-d18eff419b70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba3b9dba-5da8-4f2b-83ea-89073abfb0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger field-validation-error</value>
      <webElementGuid>3db03363-8f27-4ea8-bfdf-510388b2ad75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valmsg-for</name>
      <type>Main</type>
      <value>BP.Age</value>
      <webElementGuid>4f519027-54c5-4d51-a586-3ea31f0f610a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valmsg-replace</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e593351-68f1-4691-a96a-a6176d0c12d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The value '22.5' is not valid for Age.</value>
      <webElementGuid>45210b09-b0f0-4228-a393-625598ecf66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[4]/span[@class=&quot;text-danger field-validation-error&quot;]</value>
      <webElementGuid>732d34b5-9d2a-416a-a82d-caed1179a315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[4]/span</value>
      <webElementGuid>6412c743-1b47-4a45-a1f0-c395f1e6d619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/following::span[1]</value>
      <webElementGuid>5799f3b7-6223-4b32-a021-05db461c5708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('The value ', &quot;'&quot;, '55.5', &quot;'&quot;, ' is not valid for Diastolic.')])[1]/following::span[1]</value>
      <webElementGuid>9565609c-daea-4766-8fb4-01195674bcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[2]/preceding::span[1]</value>
      <webElementGuid>53959377-67c9-43a6-9963-f318771c5b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>f274c5b5-f4d5-4329-89c1-9825bfa912b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;The value &quot; , &quot;'&quot; , &quot;22.5&quot; , &quot;'&quot; , &quot; is not valid for Age.&quot;) or . = concat(&quot;The value &quot; , &quot;'&quot; , &quot;22.5&quot; , &quot;'&quot; , &quot; is not valid for Age.&quot;))]</value>
      <webElementGuid>ea7dfbb0-8166-478a-84a4-76ccd3eaf2c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
