<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_listError</name>
   <tag></tag>
   <elementGuidId>97970eed-369c-471e-a0d6-c314232655bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-danger.validation-summary-errors > ul > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0ad6082c-671a-47f8-b571-d70b8593008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Systolic must be greater than Diastolic</value>
      <webElementGuid>e1b4e92b-ef90-43e7-bdaf-108dd72d95d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;text-danger validation-summary-errors&quot;]/ul[1]/li[1]</value>
      <webElementGuid>c91189ef-4638-4ee1-9d0b-49e7454de7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6ddc4331-7bb0-4225-a53b-26e4ea9844e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Systolic must be greater than Diastolic</value>
      <webElementGuid>7088e26f-459a-4a77-b63a-68c06ebc1189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;text-danger validation-summary-errors&quot;]/ul[1]/li[1]</value>
      <webElementGuid>d345af94-264d-4696-8755-7130821879d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4ae8b218-3434-4390-bd99-effc99468dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Systolic must be greater than Diastolic</value>
      <webElementGuid>10db26bc-f276-4356-9127-1e11004a77ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;text-danger validation-summary-errors&quot;]/ul[1]/li[1]</value>
      <webElementGuid>5b15b322-1c5a-436d-a1ef-84a5a11d0cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9302a360-6f63-4437-97e3-a8f82b306141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Systolic must be greater than Diastolic</value>
      <webElementGuid>d87e24f4-3fb7-4900-b262-803a3e3b5e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;text-danger validation-summary-errors&quot;]/ul[1]/li[1]</value>
      <webElementGuid>2fd26479-1f7a-4890-9ab5-510368d92a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div/ul/li</value>
      <webElementGuid>1703e9bf-7d07-4e73-9fbb-77e2bbae56df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BP Category Calculator'])[1]/following::li[1]</value>
      <webElementGuid>cb3c7adf-c8cb-48d5-83d9-e31457e5fb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/following::li[1]</value>
      <webElementGuid>b52db8c5-a2e7-416e-ba43-663c62d2ca4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systolic'])[1]/preceding::li[1]</value>
      <webElementGuid>245a5a5c-fcee-4b36-ba33-04b9eb4ec7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diastolic'])[1]/preceding::li[1]</value>
      <webElementGuid>89fdb683-8318-4168-8968-228b3b30898f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Systolic must be greater than Diastolic']/parent::*</value>
      <webElementGuid>b75d0f6f-9f88-4e2b-91be-6a1cce28ae5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/ul/li</value>
      <webElementGuid>07ec491d-ef2f-4e2c-8a69-c2693dd86c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Systolic must be greater than Diastolic' or . = 'Systolic must be greater than Diastolic')]</value>
      <webElementGuid>c95b2d5f-4060-4763-a019-e617a376cd8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
