<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Diastolic field is required</name>
   <tag></tag>
   <elementGuidId>234d14c0-a157-4303-9810-d1f2db9b13b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BP_Diastolic-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BP_Diastolic-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb142e19-3837-4e72-9bf0-479aa8ce0ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>241ba416-2a62-471b-9925-8e4eca9b2080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Diastolic field is required.</value>
      <webElementGuid>6479f0fc-3ba9-4b07-b7af-0cbfc84ca34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>fadb6f8c-42d3-4b3c-95fb-fad4a510e53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6f97260-eb11-4b79-ab38-a2bd12461225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>a789fcbf-138e-4de6-b10d-d2d6df32a98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Diastolic field is required.</value>
      <webElementGuid>9b926b73-5c5f-4ab4-bccd-d7247740d0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>0316ba3d-7969-46ef-9757-9b85fc337e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>517a4e86-ba6c-4d12-8576-f13cdc1e3baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>707401ee-d0b4-4773-94e5-b3a9521e75c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Diastolic field is required.</value>
      <webElementGuid>296e8e35-c903-40b5-8447-2818a049ac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>0ded6ad6-c8be-4e99-9068-4327852faffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0d51311-a58b-4069-b7c8-6cd073dfbe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Diastolic-error</value>
      <webElementGuid>859bc485-df04-466b-9b2a-2dfae5ab802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Diastolic field is required.</value>
      <webElementGuid>a6817f18-626b-4502-aee0-b933e2b8c40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Diastolic-error&quot;)</value>
      <webElementGuid>5ad15c80-4b7f-40be-b26c-5bf8aca0cc0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BP_Diastolic-error']</value>
      <webElementGuid>8089a463-5686-4e47-882e-c414ab8090d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/span/span</value>
      <webElementGuid>18ce8609-091b-466a-90b0-f62a71f6ef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diastolic'])[1]/following::span[2]</value>
      <webElementGuid>2f8dfedb-30f3-4e55-b7da-cf52ebdd36cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Systolic field is required.'])[1]/following::span[2]</value>
      <webElementGuid>030e3877-4a0c-44b9-afd1-66df9307263e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::span[1]</value>
      <webElementGuid>e6504848-ac77-481d-abeb-8790b6e68a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Age field is required.'])[1]/preceding::span[1]</value>
      <webElementGuid>2104b654-0f8f-4dcf-9941-1e0a51743457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Diastolic field is required.']/parent::*</value>
      <webElementGuid>a84ebb3d-7ac3-4ba4-a149-2555f9ead31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span</value>
      <webElementGuid>a0e72910-aefb-4202-ab36-c0bb7ce22e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BP_Diastolic-error' and (text() = 'The Diastolic field is required.' or . = 'The Diastolic field is required.')]</value>
      <webElementGuid>e72ddb43-ed24-4c63-bab0-579cbe061ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
