<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Systolic field is required</name>
   <tag></tag>
   <elementGuidId>a3c6d787-67b5-419b-ba1f-6c3252c483d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='BP_Systolic-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BP_Systolic-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9d8d446-688e-4e80-b3af-b5868379b7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>e654ea34-580e-4e00-b03c-6df8ad168574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Systolic field is required.</value>
      <webElementGuid>9e230fd5-99d0-4ff0-a335-ae39f41e111d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>158f63dd-4885-4546-92fb-2919e4cf887f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2e28938-4a30-4375-866d-4c7be4d908d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>c8777e67-ccbd-48a6-8881-c005712c1787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Systolic field is required.</value>
      <webElementGuid>f9cbdfdf-6413-448e-8c32-73d43f0bca8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>7c3bc8fe-0e57-470f-8081-94253339ac1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2bfe418b-d911-45b2-a33a-aabb73ef394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>c49149b8-64bb-4d85-8f2c-b281b874cdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Systolic field is required.</value>
      <webElementGuid>9302e93e-b8c6-46a7-9ea9-5c3b8b8e127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>f5e5a0f5-6168-4057-9a01-51fcaee1ef5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e4bc06a-0cda-4e96-87e6-554581b0c962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BP_Systolic-error</value>
      <webElementGuid>3b3ad4c3-1a58-4462-9bbd-647e4fbcb5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Systolic field is required.</value>
      <webElementGuid>63a9164e-8481-452b-81f7-6ad9c2f0a1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BP_Systolic-error&quot;)</value>
      <webElementGuid>7e2ab6a4-bf8f-4fd2-a528-0e50b5e29607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='BP_Systolic-error']</value>
      <webElementGuid>04c08813-9d85-450a-a030-9db133c4b9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/span/span</value>
      <webElementGuid>6b3f5d02-a124-4a89-bf3e-c13f0855074c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systolic'])[1]/following::span[2]</value>
      <webElementGuid>519a33e3-f910-428c-a31a-30f62471235b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systolic must be greater than Diastolic'])[1]/following::span[2]</value>
      <webElementGuid>a5ada0bf-94cf-489b-999d-847f5db85271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diastolic'])[1]/preceding::span[1]</value>
      <webElementGuid>8e4b4f2c-b5c8-4017-8d6f-9d0f3f59c547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Diastolic field is required.'])[1]/preceding::span[1]</value>
      <webElementGuid>7de4129c-ec7c-4bd1-821d-3653e15572f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Systolic field is required.']/parent::*</value>
      <webElementGuid>b8ed2620-010b-4f6c-add3-479f4998d501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>f4e44b46-33c6-424c-bc76-5ca0ca3e5769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'BP_Systolic-error' and (text() = 'The Systolic field is required.' or . = 'The Systolic field is required.')]</value>
      <webElementGuid>23cfcc11-74c8-46e4-a852-42a8fcb480d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
