<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_Age</name>
   <tag></tag>
   <elementGuidId>48a19959-8ac4-42de-a3bb-9dd02a2aebba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP_Age</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
