<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_Email</name>
   <tag></tag>
   <elementGuidId>5d4c8a39-528b-4792-a1be-1e8cd93e875b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP_Email</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
