<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_Systolic</name>
   <tag></tag>
   <elementGuidId>13cff8b9-0831-4eb5-b8cf-98fcfc460bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP_Systolic</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
