<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_Diastolic</name>
   <tag></tag>
   <elementGuidId>c7eaaade-efe5-4d0a-b3e6-234154183334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BP_Diastolic</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
