name: Blood Presure Test Suite Monolith
on:
  workflow_dispatch:
  schedule:
    - cron: '5/25,45 01-23 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.5.2'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=1 -retryFailedTestCases=False -testSuiteCollectionPath="Test Suites/BloodPressureMonoTestCollection" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=false'
